pub mod rust_by_example;
pub mod rust_by_practice;

fn main() {
    rust_by_example();
    rust_by_practice();
}

fn rust_by_example() {
    // rust_by_example::_01_hello_world::_0_hello_world::main();
    // rust_by_example::_01_hello_world::_1_comments::main();
    // rust_by_example::_01_hello_world::_2_1_debug_1::main();
    // rust_by_example::_01_hello_world::_2_1_debug_2::main();
    // rust_by_example::_01_hello_world::_2_2_display_1_activity::main();
    // rust_by_example::_01_hello_world::_2_2_display_1::main();
    // rust_by_example::_01_hello_world::_2_2_display_2_activity::main();
    // rust_by_example::_01_hello_world::_2_2_display_2::main();
    // rust_by_example::_01_hello_world::_3_formatting::main();

    // rust_by_example::_02_primitives::_0_primitives::main();
    // rust_by_example::_02_primitives::_1_literals_and_operators::main();
    // rust_by_example::_02_primitives::_2_tuples::main();
    // rust_by_example::_02_primitives::_3_arrays_and_slices::main();

    // rust_by_example::_03_custom_types::_0_structures::main();
    // rust_by_example::_03_custom_types::_2_enums_0::main();
    // rust_by_example::_03_custom_types::_2_enums_1_use::main();
    // rust_by_example::_03_custom_types::_2_enums_2_c_like::main();
    // rust_by_example::_03_custom_types::_2_enums_3_linked_list::main();
    // rust_by_example::_03_custom_types::_3_constants::main();

    // rust_by_example::_04_variable_bindings::_0_variable_bindings::main();
    // rust_by_example::_04_variable_bindings::_1_mutability::main();
    // rust_by_example::_04_variable_bindings::_2_scope_and_shadowing_1::main();
    // rust_by_example::_04_variable_bindings::_2_scope_and_shadowing_2::main();
    // rust_by_example::_04_variable_bindings::_3_declare_first::main();
    // rust_by_example::_04_variable_bindings::_4_freezing::main();

    // rust_by_example::_05_types::_1_casting::main();
    // rust_by_example::_05_types::_2_literals::main();
    // rust_by_example::_05_types::_3_inference::main();
    // rust_by_example::_05_types::_4_aliasing::main();

    // rust_by_example::_06_conversions::_1_from_and_into::main();
    // rust_by_example::_06_conversions::_2_tryfrom_and_tryinto::main();
    // rust_by_example::_06_conversions::_3_to_and_from_strings::main();

    // rust_by_example::_07_expressions::_0_expressions::main();

    // rust_by_example::_08_flow_of_control::_1_if_else::main();
    // rust_by_example::_08_flow_of_control::_2_loop::main();
    // rust_by_example::_08_flow_of_control::_2_loop_1_nesting_and_labels::main();
    // rust_by_example::_08_flow_of_control::_2_loop_2_returning_from_loops::main();
    // rust_by_example::_08_flow_of_control::_3_while::main();
    // rust_by_example::_08_flow_of_control::_4_for_and_range::main();
    // rust_by_example::_08_flow_of_control::_5_match::main();
    // rust_by_example::_08_flow_of_control::_5_match_1_destructuring::main();
    // rust_by_example::_08_flow_of_control::_5_match_2_guards::main();
    // rust_by_example::_08_flow_of_control::_5_match_3_binding::main();
    // rust_by_example::_08_flow_of_control::_6_if_let::main();
    // rust_by_example::_08_flow_of_control::_7_let_else::main();
    // rust_by_example::_08_flow_of_control::_8_while_let::main();

    // rust_by_example::_09_functions::_0_functions::main();
    // rust_by_example::_09_functions::_1_methods::main();
    // rust_by_example::_09_functions::_2_closures::main();
    // rust_by_example::_09_functions::_2_closures_1_capturing::main();
    // rust_by_example::_09_functions::_2_closures_2_as_input_parameters::main();
    // rust_by_example::_09_functions::_2_closures_3_type_anonymity::main();
    // rust_by_example::_09_functions::_2_closures_4_input_functions::main();
    // rust_by_example::_09_functions::_2_closures_5_as_output_parameters::main();
    // rust_by_example::_09_functions::_2_closures_6_examples_in_std_1_iterator_any::main();
    // rust_by_example::_09_functions::_2_closures_6_examples_in_std_2_searching_through_iterators::main();
    // rust_by_example::_09_functions::_3_higher_order_functions::main();
    // rust_by_example::_09_functions::_4_diverging_functions::main();

    // rust_by_example::_10_modules::_1_visibility::main();
    // rust_by_example::_10_modules::_2_struct_visibility::main();
    // rust_by_example::_10_modules::_3_the_use_declaration::main();
    // rust_by_example::_10_modules::_4_super_and_self::main();
    // rust_by_example::_10_modules::_5_file_hierarchy::split::main();

    // 11.1 Creating a Library
    //   compile with: rustc --crate-type=lib src/rust_by_example/_11_crates/_1_creating_a_library.rs
    // 11.2 Using a Library
    //   compile and run with: rustc src/rust_by_example/_11_crates/_2_using_a_library.rs --extern rary=lib_1_creating_a_library.rlib && ./_2_using_a_library

    // rust_by_example::_14_generics::_0_generics::main();
    // rust_by_example::_14_generics::_1_functions::main();
    // rust_by_example::_14_generics::_2_implementation::main();
    // rust_by_example::_14_generics::_3_traits::main();
    // rust_by_example::_14_generics::_4_bounds::main();
    // rust_by_example::_14_generics::_4_bounds_1_empty_bounds::main();
    // rust_by_example::_14_generics::_5_multiple_bounds::main();
    // rust_by_example::_14_generics::_6_where_clauses::main();
    // rust_by_example::_14_generics::_7_new_type_idiom::main();
    // rust_by_example::_14_generics::_8_associated_items_1_the_problem::main();
    // rust_by_example::_14_generics::_8_associated_items_2_associated_types::main();
    // rust_by_example::_14_generics::_9_phantom_type_parameters::main();
    // rust_by_example::_14_generics::_9_phantom_type_parameters_1_unit_clarification::main();

    // rust_by_example::_15_scoping_rules::_1_raii::main();
    // rust_by_example::_15_scoping_rules::_2_ownership_and_moves::main();
    // rust_by_example::_15_scoping_rules::_2_ownership_and_moves_1_mutability::main();
    // rust_by_example::_15_scoping_rules::_2_ownership_and_moves_2_partial_moves::main();
    // rust_by_example::_15_scoping_rules::_3_borrowing::main();
    // rust_by_example::_15_scoping_rules::_3_borrowing_1_mutability::main();
    // rust_by_example::_15_scoping_rules::_3_borrowing_2_aliasing::main();
    // rust_by_example::_15_scoping_rules::_3_borrowing_3_the_ref_pattern::main();
    // rust_by_example::_15_scoping_rules::_4_lifetimes_1_explicit_annotation::main();
    // rust_by_example::_15_scoping_rules::_4_lifetimes_2_functions::main();
    // rust_by_example::_15_scoping_rules::_4_lifetimes_3_methods::main();
    // rust_by_example::_15_scoping_rules::_4_lifetimes_4_structs::main();
    // rust_by_example::_15_scoping_rules::_4_lifetimes_5_traits::main();
    // rust_by_example::_15_scoping_rules::_4_lifetimes_6_bounds::main();
    // rust_by_example::_15_scoping_rules::_4_lifetimes_7_coercion::main();
    // rust_by_example::_15_scoping_rules::_4_lifetimes_8_static_reference_lifetime::main();
    // rust_by_example::_15_scoping_rules::_4_lifetimes_8_static_trait_bound::main();
    // rust_by_example::_15_scoping_rules::_4_lifetimes_9_elision::main();

    // rust_by_example::_16_traits::_0_traits::main();
    // rust_by_example::_16_traits::_1_derive::main();
    // rust_by_example::_16_traits::_2_returning_traits_with_dyn::main();
    // rust_by_example::_16_traits::_3_operator_overloading::main();
    // rust_by_example::_16_traits::_4_drop::main();
    // rust_by_example::_16_traits::_5_iterators::main();
    // rust_by_example::_16_traits::_6_impl_trait_1_as_an_argument_type::main();
    // rust_by_example::_16_traits::_6_impl_trait_2_as_a_return_type::main();
    // rust_by_example::_16_traits::_6_impl_trait_3_as_a_return_type::main();
    // rust_by_example::_16_traits::_6_impl_trait_4_as_a_return_type::main();
    // rust_by_example::_16_traits::_7_clone::main();
    // rust_by_example::_16_traits::_8_supertraits::main();
    // rust_by_example::_16_traits::_9_disambiguating_overlapping_traits::main();

    // rust_by_example::_17_macro_rules::_0_macro_rules::main();
    // rust_by_example::_17_macro_rules::_1_syntax_1_designators::main();
    // rust_by_example::_17_macro_rules::_1_syntax_2_overload::main();
    // rust_by_example::_17_macro_rules::_1_syntax_3_repeat::main();
    // rustc --test src/rust_by_example/_17_macro_rules/_2_dry.rs && ./_2_dry
    // rust_by_example::_17_macro_rules::_3_dsl::main();
    // rust_by_example::_17_macro_rules::_4_variadic_interfaces::main();

    // rust_by_example::_18_error_handling::_1_panic::main();
    // rustc src/rust_by_example/_18_error_handling/_2_abort_and_unwind_1.rs -C panic=abort && ./_2_abort_and_unwind_1
    // // rust_by_example::_18_error_handling::_2_abort_and_unwind_1::main();
    // rust_by_example::_18_error_handling::_2_abort_and_unwind_2::main();
    // rust_by_example::_18_error_handling::_3_option_and_unwrap::main();
    // rust_by_example::_18_error_handling::_3_option_and_unwrap_1_unpacking_options_with_questionmark::main();
    // rust_by_example::_18_error_handling::_3_option_and_unwrap_2_combinators_map::main();
    // rust_by_example::_18_error_handling::_3_option_and_unwrap_3_combinators_and_then::main();
    // rust_by_example::_18_error_handling::_3_option_and_unwrap_4_unpacking_options_and_defaults::main();
    // rust_by_example::_18_error_handling::_4_result::main();
    // rust_by_example::_18_error_handling::_4_result_main::main();
    // rust_by_example::_18_error_handling::_4_result_1_map_for_result_1::main();
    // rust_by_example::_18_error_handling::_4_result_1_map_for_result_2::main();
    // rust_by_example::_18_error_handling::_4_result_2_aliases_for_result::main();
    // rust_by_example::_18_error_handling::_4_result_3_early_returns::main();
    // rust_by_example::_18_error_handling::_4_result_4_introducing_questionmark_1::main();
    // rust_by_example::_18_error_handling::_4_result_4_introducing_questionmark_2_try_macro::main();
    // rust_by_example::_18_error_handling::_5_multiple_error_types::main();
    // rust_by_example::_18_error_handling::_5_multiple_error_types_1_pulling_results_out_of_options_1::main();
    // rust_by_example::_18_error_handling::_5_multiple_error_types_1_pulling_results_out_of_options_2::main();
    // rust_by_example::_18_error_handling::_5_multiple_error_types_2_defining_an_error_type::main();
    // rust_by_example::_18_error_handling::_5_multiple_error_types_3_boxing_errors::main();
    // rust_by_example::_18_error_handling::_5_multiple_error_types_4_other_uses_of_questionmark::main();
    // rust_by_example::_18_error_handling::_5_multiple_error_types_5_wrapping_errors::main();
    // rust_by_example::_18_error_handling::_6_iterating_over_results::main();

    // rust_by_example::_19_std_library_types::_1_box_stack_and_heap::main();
    // rust_by_example::_19_std_library_types::_2_vectors::main();
    // rust_by_example::_19_std_library_types::_3_strings_1::main();
    // rust_by_example::_19_std_library_types::_3_strings_2_literals_and_escapes::main();
    // rust_by_example::_19_std_library_types::_3_strings_3_literals_and_escapes::main();
    // rust_by_example::_19_std_library_types::_3_strings_4_literals_and_escapes::main();
    // rust_by_example::_19_std_library_types::_4_option::main();
    // rust_by_example::_19_std_library_types::_5_result::main();
    // rust_by_example::_19_std_library_types::_5_result_1_questionmark::main();
    // rust_by_example::_19_std_library_types::_6_panic::main();
    // rust_by_example::_19_std_library_types::_7_hashmap::main();
    // rust_by_example::_19_std_library_types::_7_hashmap_1_alternate_custom_key_types::main();
    // rust_by_example::_19_std_library_types::_7_hashmap_2_hashset::main();
    // rust_by_example::_19_std_library_types::_8_rc::main();
    // rust_by_example::_19_std_library_types::_9_arc::main();

    // rust_by_example::_20_std_misc::_1_threads::main();
    // rust_by_example::_20_std_misc::_1_threads_1_testcase_mapreduce::main();
    // rust_by_example::_20_std_misc::_2_channels::main();
    // rust_by_example::_20_std_misc::_3_path::main();
    // rust_by_example::_20_std_misc::_4_file_io_1_open::main();
    // rust_by_example::_20_std_misc::_4_file_io_2_create::main();
    // rust_by_example::_20_std_misc::_4_file_io_3_read_lines::main();
    // rust_by_example::_20_std_misc::_5_child_processes::main();
    // rust_by_example::_20_std_misc::_5_child_processes_1_pipes::main();
    // rust_by_example::_20_std_misc::_5_child_processes_2_wait::main();
    // rust_by_example::_20_std_misc::_6_filesystem_operations::main();
    // rust_by_example::_20_std_misc::_7_program_arguments::main();
    // rust_by_example::_20_std_misc::_7_program_arguments_1_argument_parsing::main();
    // rust_by_example::_20_std_misc::_8_foreign_function_interface::main();
}

fn rust_by_practice() {
    // rust_by_practice::_03_variables::_0_variables_1_binding_and_mutability::main();
    // rust_by_practice::_03_variables::_0_variables_2_binding_and_mutability::main();
    // rust_by_practice::_03_variables::_0_variables_3_scope::main();
    // rust_by_practice::_03_variables::_0_variables_4_scope::main();
    // rust_by_practice::_03_variables::_0_variables_5_shadowing::main();
    // rust_by_practice::_03_variables::_0_variables_6_shadowing::main();
    // rust_by_practice::_03_variables::_0_variables_7_unused_variables::main();
    // rust_by_practice::_03_variables::_0_variables_8_destructuring::main();
    // rust_by_practice::_03_variables::_0_variables_9_destructuring_assignments::main();

    // rust_by_practice::_04_basic_types::_1_numbers_1_integer::main();
    // rust_by_practice::_04_basic_types::_1_numbers_2_integer::main();
    // rust_by_practice::_04_basic_types::_1_numbers_3_integer::main();
    // rust_by_practice::_04_basic_types::_1_numbers_4_integer::main();
    // rust_by_practice::_04_basic_types::_1_numbers_5_integer::main();
    // rust_by_practice::_04_basic_types::_1_numbers_6_integer::main();
    // rust_by_practice::_04_basic_types::_1_numbers_7_floating_point::main();
    // rust_by_practice::_04_basic_types::_1_numbers_8_floating_point::main();
    // rust_by_practice::_04_basic_types::_1_numbers_9_range::main();
    // rust_by_practice::_04_basic_types::_1_numbers_10_range::main();
    // rust_by_practice::_04_basic_types::_1_numbers_11_computations::main();
    // rust_by_practice::_04_basic_types::_2_cbu_1_char::main();
    // rust_by_practice::_04_basic_types::_2_cbu_2_char::main();
    // rust_by_practice::_04_basic_types::_2_cbu_3_bool::main();
    // rust_by_practice::_04_basic_types::_2_cbu_4_bool::main();
    // rust_by_practice::_04_basic_types::_2_cbu_5_unit::main();
    // rust_by_practice::_04_basic_types::_2_cbu_6_unit::main();
    // rust_by_practice::_04_basic_types::_3_statements_expressions_0::main();
    // rust_by_practice::_04_basic_types::_3_statements_expressions_1::main();
    // rust_by_practice::_04_basic_types::_3_statements_expressions_2::main();
    // rust_by_practice::_04_basic_types::_3_statements_expressions_3::main();
    // rust_by_practice::_04_basic_types::_4_functions_1::main();
    // rust_by_practice::_04_basic_types::_4_functions_2::main();
    // rust_by_practice::_04_basic_types::_4_functions_3::main();
    // rust_by_practice::_04_basic_types::_4_functions_4_diverging::main();
    // rust_by_practice::_04_basic_types::_4_functions_5_diverging::main();
    
    // rust_by_practice::_05_ownership_and_borrowing::_1_ownership_1::main();
    // rust_by_practice::_05_ownership_and_borrowing::_1_ownership_2::main();
    // rust_by_practice::_05_ownership_and_borrowing::_1_ownership_3::main();
    // rust_by_practice::_05_ownership_and_borrowing::_1_ownership_4::main();
    // rust_by_practice::_05_ownership_and_borrowing::_1_ownership_5::main();
    // rust_by_practice::_05_ownership_and_borrowing::_1_ownership_6_mutability::main();
    // rust_by_practice::_05_ownership_and_borrowing::_1_ownership_7_mutability::main();
    // rust_by_practice::_05_ownership_and_borrowing::_1_ownership_8_partial_move_example::main();
    // rust_by_practice::_05_ownership_and_borrowing::_1_ownership_8_partial_move::main();
    // rust_by_practice::_05_ownership_and_borrowing::_1_ownership_9_partial_move::main();
    // rust_by_practice::_05_ownership_and_borrowing::_2_referencing_and_borrowing_1_reference::main();
    // rust_by_practice::_05_ownership_and_borrowing::_2_referencing_and_borrowing_2_reference::main();
    // rust_by_practice::_05_ownership_and_borrowing::_2_referencing_and_borrowing_3_reference::main();
    // rust_by_practice::_05_ownership_and_borrowing::_2_referencing_and_borrowing_4_reference::main();
    // rust_by_practice::_05_ownership_and_borrowing::_2_referencing_and_borrowing_5_reference::main();
    // rust_by_practice::_05_ownership_and_borrowing::_2_referencing_and_borrowing_6_ref::main();
    // rust_by_practice::_05_ownership_and_borrowing::_2_referencing_and_borrowing_7_borrowing_rules::main();
    // rust_by_practice::_05_ownership_and_borrowing::_2_referencing_and_borrowing_8_mutablity::main();
    // rust_by_practice::_05_ownership_and_borrowing::_2_referencing_and_borrowing_9_mutablity::main();
    // rust_by_practice::_05_ownership_and_borrowing::_2_referencing_and_borrowing_10_nll::main();
    // rust_by_practice::_05_ownership_and_borrowing::_2_referencing_and_borrowing_11_nll::main();

    // rust_by_practice::_06_compound_types::_1_string_1_str_and_str::main();
    // rust_by_practice::_06_compound_types::_1_string_2_str_and_str::main();
    // rust_by_practice::_06_compound_types::_1_string_3_string::main();
    // rust_by_practice::_06_compound_types::_1_string_4_string::main();
    // rust_by_practice::_06_compound_types::_1_string_5_string::main();
    // rust_by_practice::_06_compound_types::_1_string_6_string::main();
    // rust_by_practice::_06_compound_types::_1_string_7_str_and_string::main();
    // rust_by_practice::_06_compound_types::_1_string_8_str_and_string::main();
    // rust_by_practice::_06_compound_types::_1_string_9_string_escapes::main();
    // rust_by_practice::_06_compound_types::_1_string_10_string_escapes::main();
    // rust_by_practice::_06_compound_types::_1_string_11_byte_string_example::main();
    // rust_by_practice::_06_compound_types::_1_string_11_string_index::main();
    // rust_by_practice::_06_compound_types::_1_string_12_operate_on_utf8_string::main();
    // rust_by_practice::_06_compound_types::_1_string_12_utf8_slice_example::main();
    // rust_by_practice::_06_compound_types::_2_array_1::main();
    // rust_by_practice::_06_compound_types::_2_array_2::main();
    // rust_by_practice::_06_compound_types::_2_array_3::main();
    // rust_by_practice::_06_compound_types::_2_array_4::main();
    // rust_by_practice::_06_compound_types::_2_array_5::main();
    // rust_by_practice::_06_compound_types::_2_array_6::main();
    // rust_by_practice::_06_compound_types::_3_slice_1::main();
    // rust_by_practice::_06_compound_types::_3_slice_2::main();
    // rust_by_practice::_06_compound_types::_3_slice_3::main();
    // rust_by_practice::_06_compound_types::_3_slice_4_string_slices::main();
    // rust_by_practice::_06_compound_types::_3_slice_5_string_slices::main();
    // rust_by_practice::_06_compound_types::_3_slice_6_string_slices::main();
    // rust_by_practice::_06_compound_types::_4_tuple_1::main();
    // rust_by_practice::_06_compound_types::_4_tuple_2::main();
    // rust_by_practice::_06_compound_types::_4_tuple_3::main();
    // rust_by_practice::_06_compound_types::_4_tuple_4::main();
    // rust_by_practice::_06_compound_types::_4_tuple_5::main();
    // rust_by_practice::_06_compound_types::_4_tuple_6::main();
    // rust_by_practice::_06_compound_types::_5_struct_1_the_types_of_structs::main();
    // rust_by_practice::_06_compound_types::_5_struct_2_the_types_of_structs::main();
    // rust_by_practice::_06_compound_types::_5_struct_3_the_types_of_structs::main();
    // rust_by_practice::_06_compound_types::_5_struct_4_operating_on_structs::main();
    // rust_by_practice::_06_compound_types::_5_struct_5_operating_on_structs::main();
    // rust_by_practice::_06_compound_types::_5_struct_6_operating_on_structs::main();
    // rust_by_practice::_06_compound_types::_5_struct_7_print_the_structs::main();
    // rust_by_practice::_06_compound_types::_5_struct_8_partial_move_example::main();
    // rust_by_practice::_06_compound_types::_5_struct_8_partial_move::main();
    // rust_by_practice::_06_compound_types::_6_enum_1::main();
    // rust_by_practice::_06_compound_types::_6_enum_2::main();
    // rust_by_practice::_06_compound_types::_6_enum_3::main();
    // rust_by_practice::_06_compound_types::_6_enum_4::main();
    // rust_by_practice::_06_compound_types::_6_enum_5::main();
    // rust_by_practice::_06_compound_types::_6_enum_6::main();

    // rust_by_practice::_07_flow_control::_1_flow_control_1_if_else::main();
    // rust_by_practice::_07_flow_control::_1_flow_control_2_if_else::main();
    // rust_by_practice::_07_flow_control::_1_flow_control_3_for::main();
    // rust_by_practice::_07_flow_control::_1_flow_control_4_for::main();
    // rust_by_practice::_07_flow_control::_1_flow_control_5_for::main();
    // rust_by_practice::_07_flow_control::_1_flow_control_6_while::main();
    // rust_by_practice::_07_flow_control::_1_flow_control_7_continue_and_break::main();
    // rust_by_practice::_07_flow_control::_1_flow_control_8_continue_and_break::main();
    // rust_by_practice::_07_flow_control::_1_flow_control_9_loop::main();
    // rust_by_practice::_07_flow_control::_1_flow_control_10_loop::main();
    // rust_by_practice::_07_flow_control::_1_flow_control_11_loop::main();

    // rust_by_practice::_08_pattern_match::_1_match_matches_and_if_let_1_match::main();
    // rust_by_practice::_08_pattern_match::_1_match_matches_and_if_let_2_match::main();
    // rust_by_practice::_08_pattern_match::_1_match_matches_and_if_let_3_match::main();
    // rust_by_practice::_08_pattern_match::_1_match_matches_and_if_let_4_matches::main();
    // rust_by_practice::_08_pattern_match::_1_match_matches_and_if_let_5_matches::main();
    // rust_by_practice::_08_pattern_match::_1_match_matches_and_if_let_6_if_let::main();
    // rust_by_practice::_08_pattern_match::_1_match_matches_and_if_let_7_if_let::main();
    // rust_by_practice::_08_pattern_match::_1_match_matches_and_if_let_8_if_let::main();
    // rust_by_practice::_08_pattern_match::_1_match_matches_and_if_let_9_shadowing::main();
    // rust_by_practice::_08_pattern_match::_2_patterns_1::main();
    // rust_by_practice::_08_pattern_match::_2_patterns_2::main();
    // rust_by_practice::_08_pattern_match::_2_patterns_3::main();
    // rust_by_practice::_08_pattern_match::_2_patterns_4::main();
    // rust_by_practice::_08_pattern_match::_2_patterns_5::main();
    // rust_by_practice::_08_pattern_match::_2_patterns_6::main();

    // rust_by_practice::_09_method_and_associated_function::_0_method_and_associated_function_1_method::main();
    // rust_by_practice::_09_method_and_associated_function::_0_method_and_associated_function_2_method::main();
    // rust_by_practice::_09_method_and_associated_function::_0_method_and_associated_function_3_method::main();
    // rust_by_practice::_09_method_and_associated_function::_0_method_and_associated_function_4_associated_functions::main();
    // rust_by_practice::_09_method_and_associated_function::_0_method_and_associated_function_5_multiple_impl_blocks::main();
    // rust_by_practice::_09_method_and_associated_function::_0_method_and_associated_function_6_enums::main();

    // rust_by_practice::_10_generics_and_traits::_1_generics_1_functions::main();
    // rust_by_practice::_10_generics_and_traits::_1_generics_2_functions::main();
    // rust_by_practice::_10_generics_and_traits::_1_generics_3_struct_and_impl::main();
    // rust_by_practice::_10_generics_and_traits::_1_generics_4_struct_and_impl::main();
    // rust_by_practice::_10_generics_and_traits::_1_generics_5_struct_and_impl::main();
    // rust_by_practice::_10_generics_and_traits::_1_generics_6_method::main();
    // rust_by_practice::_10_generics_and_traits::_1_generics_7_method::main();
    // rust_by_practice::_10_generics_and_traits::_2_const_generics_1::main();
    // rust_by_practice::_10_generics_and_traits::_2_const_generics_2::main();
    // rust_by_practice::_10_generics_and_traits::_2_const_generics_3::main();
    // rust_by_practice::_10_generics_and_traits::_3_traits_1_example::main();
    // rust_by_practice::_10_generics_and_traits::_3_traits_1::main();
    // rust_by_practice::_10_generics_and_traits::_3_traits_2_derive::main();
    // rust_by_practice::_10_generics_and_traits::_3_traits_3_operator::main();
    // rust_by_practice::_10_generics_and_traits::_3_traits_4_operator::main();
    // rust_by_practice::_10_generics_and_traits::_3_traits_5_use_trait_as_function_parameters::main();
    // rust_by_practice::_10_generics_and_traits::_3_traits_6_returning_types_that_implement_traits::main();
    // rust_by_practice::_10_generics_and_traits::_3_traits_7_trait_bound::main();
    // rust_by_practice::_10_generics_and_traits::_3_traits_8_trait_bound::main();
    // rust_by_practice::_10_generics_and_traits::_3_traits_9_trait_bound::main();
    // rust_by_practice::_10_generics_and_traits::_4_trait_object_1_returning_traits_with_dyn::main();
    // rust_by_practice::_10_generics_and_traits::_4_trait_object_2_array_with_trait_objects::main();
    // rust_by_practice::_10_generics_and_traits::_4_trait_object_3_dyn_and_box_dyn::main();
    // rust_by_practice::_10_generics_and_traits::_4_trait_object_4_static_and_dynamic_dispatch::main();
    // rust_by_practice::_10_generics_and_traits::_4_trait_object_5_object_safe::main();
    // rust_by_practice::_10_generics_and_traits::_5_advanced_traits_1_associated_types::main();
    // rust_by_practice::_10_generics_and_traits::_5_advanced_traits_2_default_generic_type_parameters::main();
    // rust_by_practice::_10_generics_and_traits::_5_advanced_traits_3_fully_qualified_syntax_example::main();
    // rust_by_practice::_10_generics_and_traits::_5_advanced_traits_3_fully_qualified_syntax::main();
    // rust_by_practice::_10_generics_and_traits::_5_advanced_traits_4_supertraits::main();
    // rust_by_practice::_10_generics_and_traits::_5_advanced_traits_5_orphan_rules::main();

    // rust_by_practice::_11_collection_types::_1_string_1_basic_operations::main();
    // rust_by_practice::_11_collection_types::_1_string_2_string_and_str::main();
    // rust_by_practice::_11_collection_types::_1_string_3_string_and_str::main();
    // rust_by_practice::_11_collection_types::_1_string_4_utf8_and_indexing::main();
    // rust_by_practice::_11_collection_types::_1_string_5_utf8_slice::main();
    // rust_by_practice::_11_collection_types::_1_string_6_representation::main();
    // rust_by_practice::_11_collection_types::_1_string_7_representation::main();
    // rust_by_practice::_11_collection_types::_2_vector_1_basic_operations::main();
    // rust_by_practice::_11_collection_types::_2_vector_2_basic_operations::main();
    // rust_by_practice::_11_collection_types::_2_vector_3_turn_x_into_vec::main();
    // rust_by_practice::_11_collection_types::_2_vector_4_indexing::main();
    // rust_by_practice::_11_collection_types::_2_vector_5_slicing::main();
    // rust_by_practice::_11_collection_types::_2_vector_6_capacity::main();
    // rust_by_practice::_11_collection_types::_2_vector_7_store_distinct_types_in_vector::main();
    // rust_by_practice::_11_collection_types::_2_vector_8_store_distinct_types_in_vector::main();
    // rust_by_practice::_11_collection_types::_3_hashmap_1_basic_operations::main();
    // rust_by_practice::_11_collection_types::_3_hashmap_2_basic_operations::main();
    // rust_by_practice::_11_collection_types::_3_hashmap_3_basic_operations::main();
    // rust_by_practice::_11_collection_types::_3_hashmap_4_requirements_of_hashmap_key::main();
    // rust_by_practice::_11_collection_types::_3_hashmap_4_capacity_example::main();
    // rust_by_practice::_11_collection_types::_3_hashmap_5_ownership::main();

    // rust_by_practice::_12_type_conversion::_1_as_1::main();
    // rust_by_practice::_12_type_conversion::_1_as_2::main();
    // rust_by_practice::_12_type_conversion::_1_as_3::main();
    // rust_by_practice::_12_type_conversion::_1_as_4::main();
    // rust_by_practice::_12_type_conversion::_1_as_5::main();
    // rust_by_practice::_12_type_conversion::_2_from_into_1::main();
    // rust_by_practice::_12_type_conversion::_2_from_into_2::main();
    // rust_by_practice::_12_type_conversion::_2_from_into_3::main();
    // rust_by_practice::_12_type_conversion::_2_from_into_4_tryfrom_tryinto::main();
    // rust_by_practice::_12_type_conversion::_2_from_into_5_tryfrom_tryinto::main();
    // rust_by_practice::_12_type_conversion::_3_others_1_convert_any_type_to_string::main();
    // rust_by_practice::_12_type_conversion::_3_others_2_parse_a_string::main();
    // rust_by_practice::_12_type_conversion::_3_others_3_parse_a_string::main();
    // rust_by_practice::_12_type_conversion::_3_others_transmute_examples_1::main();
    // rust_by_practice::_12_type_conversion::_3_others_transmute_examples_3::main();

    // rust_by_practice::_13_result_and_panic::_1_panic_1::main();
    // rust_by_practice::_13_result_and_panic::_1_panic_2::main();
    // rust_by_practice::_13_result_and_panic::_2_result_and_questionmark_1::main();
    // rust_by_practice::_13_result_and_panic::_2_result_and_questionmark_2_questionmark::main();
    // rust_by_practice::_13_result_and_panic::_2_result_and_questionmark_3_questionmark::main();
    // rust_by_practice::_13_result_and_panic::_2_result_and_questionmark_4_map_and_then::main();
    // rust_by_practice::_13_result_and_panic::_2_result_and_questionmark_5_map_and_then::main();
    // rust_by_practice::_13_result_and_panic::_2_result_and_questionmark_6_type_alias::main();
    // rust_by_practice::_13_result_and_panic::_2_result_and_questionmark_using_result_in_fn_main::main();

    // rust_by_practice::_16_formatted_output::_0_formatted_output::main();
    // rust_by_practice::_16_formatted_output::_1_println_and_format_1_format::main();
    // rust_by_practice::_16_formatted_output::_1_println_and_format_2_print_println::main();
    // rust_by_practice::_16_formatted_output::_2_debug_and_display_1_debug::main();
    // rust_by_practice::_16_formatted_output::_2_debug_and_display_2_debug::main();
    // rust_by_practice::_16_formatted_output::_2_debug_and_display_3_debug::main();
    // rust_by_practice::_16_formatted_output::_2_debug_and_display_4_display::main();
    // rust_by_practice::_16_formatted_output::_2_debug_and_display_5_questionmark_operator::main();
    // rust_by_practice::_16_formatted_output::_3_formatting_1_positional_arguments::main();
    // rust_by_practice::_16_formatted_output::_3_formatting_2_named_arguments::main();
    // rust_by_practice::_16_formatted_output::_3_formatting_3_padding_with_strings::main();
    // rust_by_practice::_16_formatted_output::_3_formatting_4_padding_with_strings::main();
    // rust_by_practice::_16_formatted_output::_3_formatting_5_padding_with_strings::main();
    // rust_by_practice::_16_formatted_output::_3_formatting_6_precision::main();
    // rust_by_practice::_16_formatted_output::_3_formatting_7_precision::main();
    // rust_by_practice::_16_formatted_output::_3_formatting_8_binary_octal_hex::main();
    // rust_by_practice::_16_formatted_output::_3_formatting_9_capture_the_environment::main();
    // rust_by_practice::_16_formatted_output::_3_formatting_others::main();

    // rust_by_practice::_17_lifetime::_1_basic_1_scope::main();
    // rust_by_practice::_17_lifetime::_1_basic_2_example::main();
    // rust_by_practice::_17_lifetime::_1_basic_3_function_example::main();
    // rust_by_practice::_17_lifetime::_1_basic_3_function::main();
    // rust_by_practice::_17_lifetime::_1_basic_4_function::main();
    // rust_by_practice::_17_lifetime::_1_basic_5_function::main();
    // rust_by_practice::_17_lifetime::_1_basic_6_structs::main();
    // rust_by_practice::_17_lifetime::_1_basic_7_structs::main();
    // rust_by_practice::_17_lifetime::_1_basic_8_structs::main();
    // rust_by_practice::_17_lifetime::_1_basic_9_method_example::main();
    // rust_by_practice::_17_lifetime::_1_basic_9_method::main();
    // rust_by_practice::_17_lifetime::_1_basic_10_elision::main();
    // rust_by_practice::_17_lifetime::_2_static_and_t_static_1_static::main();
    // rust_by_practice::_17_lifetime::_2_static_and_t_static_2_static::main();
    // rust_by_practice::_17_lifetime::_2_static_and_t_static_3_static::main();
    // rust_by_practice::_17_lifetime::_2_static_and_t_static_4_static_example::main();
    // rust_by_practice::_17_lifetime::_2_static_and_t_static_5_t_static::main();
    // rust_by_practice::_17_lifetime::_2_static_and_t_static_6_t_static::main();
    // rust_by_practice::_17_lifetime::_3_advanced_1_trait_bounds_example::main();
    // rust_by_practice::_17_lifetime::_3_advanced_1_trait_bounds::main();
    // rust_by_practice::_17_lifetime::_3_advanced_2_trait_bounds::main();
    // rust_by_practice::_17_lifetime::_3_advanced_3_trait_bounds::main();
    // rust_by_practice::_17_lifetime::_3_advanced_4_hrtb::main();
    // rust_by_practice::_17_lifetime::_3_advanced_5_reborrow_example::main();
    // rust_by_practice::_17_lifetime::_3_advanced_5_reborrow::main();
    // rust_by_practice::_17_lifetime::_3_advanced_6_difficult_exercise::main();

    // rust_by_practice::_18_functional_programming::_1_closure_1_capturing::main();
    // rust_by_practice::_18_functional_programming::_1_closure_2_capturing::main();
    // rust_by_practice::_18_functional_programming::_1_closure_3_capturing::main();
    // rust_by_practice::_18_functional_programming::_1_closure_4_type_inferred::main();
    // rust_by_practice::_18_functional_programming::_1_closure_5_fn_fnmut_fnonce::main();
    // rust_by_practice::_18_functional_programming::_1_closure_6_fn_fnmut_fnonce::main();
    // rust_by_practice::_18_functional_programming::_1_closure_7_fn_fnmut_fnonce::main();
    // rust_by_practice::_18_functional_programming::_1_closure_8_fn_fnmut_fnonce::main();
    // rust_by_practice::_18_functional_programming::_1_closure_9_input_functions::main();
    // rust_by_practice::_18_functional_programming::_1_closure_10_closure_as_return_types::main();
    // rust_by_practice::_18_functional_programming::_1_closure_11_closure_as_return_types::main();
    // rust_by_practice::_18_functional_programming::_1_closure_closures_in_structs_example::main();
    // rust_by_practice::_18_functional_programming::_2_iterator_1_for_and_iterator::main();
    // rust_by_practice::_18_functional_programming::_2_iterator_2_for_and_iterator::main();
    // rust_by_practice::_18_functional_programming::_2_iterator_3_next_method::main();
    // rust_by_practice::_18_functional_programming::_2_iterator_4_intoiter_iter_and_itermut::main();
    // rust_by_practice::_18_functional_programming::_2_iterator_5_intoiter_iter_and_itermut::main();
    // rust_by_practice::_18_functional_programming::_2_iterator_6_intoiter_iter_and_itermut::main();
    // rust_by_practice::_18_functional_programming::_2_iterator_7_creating_our_own_iterator_example::main();
    // rust_by_practice::_18_functional_programming::_2_iterator_7_creating_our_own_iterator::main();
    // rust_by_practice::_18_functional_programming::_2_iterator_8_consuming_adaptors::main();
    // rust_by_practice::_18_functional_programming::_2_iterator_9_collect::main();
    // rust_by_practice::_18_functional_programming::_2_iterator_10_iterator_adaptors::main();
    // rust_by_practice::_18_functional_programming::_2_iterator_11_iterator_adaptors::main();
    // rust_by_practice::_18_functional_programming::_2_iterator_12_using_closures_in_iterator_adaptors::main();

    // rust_by_practice::_19_newtype_and_dst::_0_newtype_and_dst_1_newtype::main();
    // rust_by_practice::_19_newtype_and_dst::_0_newtype_and_dst_2_newtype::main();
    // rust_by_practice::_19_newtype_and_dst::_0_newtype_and_dst_3_newtype::main();
    // rust_by_practice::_19_newtype_and_dst::_0_newtype_and_dst_4_newtype::main();
    // rust_by_practice::_19_newtype_and_dst::_0_newtype_and_dst_5_type_alias::main();
    // rust_by_practice::_19_newtype_and_dst::_0_newtype_and_dst_6_type_alias::main();
    // rust_by_practice::_19_newtype_and_dst::_0_newtype_and_dst_7_dst_and_unsized_type::main();
    // rust_by_practice::_19_newtype_and_dst::_0_newtype_and_dst_8_dst_and_unsized_type::main();
    // rust_by_practice::_19_newtype_and_dst::_0_newtype_and_dst_9_dst_and_unsized_type::main();

    // rust_by_practice::_31_fighting_with_compiler::_1_borrowing_1::main();
}